application: fieldtripapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /updateAllPhotos
  script: updateAllPhotos.py
  login: admin
- url: /.*
  script: main.py
